name: Deploy Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Укажи нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Railway
        run: |
          curl -X POST https://railway.app/api/v1/projects/a8040121-069d-4ad8-8c8d-72bd2221d00f/deploy \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
